# Generated by Django 6.0.2 on 2026-02-21 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_seconds', models.FloatField(default=0)),
                ('idle_seconds', models.FloatField(default=0)),
                ('total_seconds', models.FloatField(default=0)),
                ('productivity_ratio', models.FloatField(default=0, help_text='0.0 to 1.0')),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_interval_seconds', models.PositiveIntegerField(default=300, help_text='How often to take screenshots (in seconds)')),
                ('activity_report_interval_seconds', models.PositiveIntegerField(default=60, help_text='How often to send activity reports (in seconds)')),
                ('idle_threshold_seconds', models.PositiveIntegerField(default=120, help_text='Seconds of no input before marking as idle')),
                ('screenshot_quality', models.PositiveSmallIntegerField(default=60, help_text='JPEG quality (1-100)')),
                ('tracking_enabled', models.BooleanField(default=True, help_text='Master switch to enable/disable all tracking')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Agent Settings',
            },
        ),
        migrations.CreateModel(
            name='AppUsageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=200)),
                ('window_title', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('activity_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_entries', to='monitoring.activitylog')),
            ],
            options={
                'ordering': ['-duration_seconds'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Internal employee ID', max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('pc_name', models.CharField(blank=True, help_text='Computer name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_token', to='monitoring.employee')),
            ],
        ),
        migrations.AddField(
            model_name='activitylog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='monitoring.employee'),
        ),
        migrations.CreateModel(
            name='ProductivityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('domain', 'Website Domain'), ('app', 'Application')], max_length=10)),
                ('pattern', models.CharField(help_text="Domain name (e.g. 'github.com') or app name (e.g. 'code.exe')", max_length=200)),
                ('category', models.CharField(choices=[('productive', 'Productive'), ('unproductive', 'Unproductive'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['match_type', 'pattern'],
                'unique_together': {('match_type', 'pattern')},
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/%d/')),
                ('monitor_index', models.PositiveSmallIntegerField(default=1)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('captured_at', models.DateTimeField(help_text='When the screenshot was taken on the employee PC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='monitoring.employee')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['employee', '-created_at'], name='monitoring__employe_b2cffc_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['employee', '-captured_at'], name='monitoring__employe_2701dd_idx'),
        ),
    ]
