# Generated by Django 5.2.9 on 2026-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Semver e.g. 1.1.0', max_length=20, unique=True)),
                ('package', models.FileField(upload_to='agent_packages/')),
                ('notes', models.TextField(blank=True, help_text='What changed in this version')),
                ('is_active', models.BooleanField(default=True, help_text='Serve this version to agents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
