# Generated by Django 5.2.9 on 2026-03-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_add_agent_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusageentry',
            name='domain',
            field=models.CharField(blank=True, default='', help_text='Extracted website domain when the active app is a browser', max_length=200),
        ),
    ]
