# Generated by Django 5.2.9 on 2026-03-20 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_add_domain_to_appusageentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('overtime', 'Overtime Info'), ('schedule', 'Schedule Info'), ('custom', 'Custom Message')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the agent displayed the toast', null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitoring.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', '-created_at'], name='monitoring__employe_798d77_idx'), models.Index(fields=['employee', 'delivered_at'], name='monitoring__employe_883de3_idx')],
            },
        ),
    ]
