# Generated by Django 5.2.9 on 2026-03-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_add_agent_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='agent_version',
            field=models.CharField(blank=True, default='', help_text='Agent version reported at last check-in', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Last known IP from agent check-in', null=True),
        ),
    ]
