# Generated by Django 5.2.9 on 2026-03-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_employee_agent_version_employee_last_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='local_ip',
            field=models.GenericIPAddressField(blank=True, help_text='LAN IP reported by agent', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Public IP from agent check-in', null=True),
        ),
    ]
