# Generated by Django 5.2.9 on 2026-03-30 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_employee_local_ip_alter_employee_last_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockTimeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date this override applies to')),
                ('clock_in_override', models.TimeField(blank=True, help_text='Override clock-in time (local SAST). Leave blank to keep auto-detected.', null=True)),
                ('clock_out_override', models.TimeField(blank=True, help_text='Override clock-out time (local SAST). Leave blank to keep auto-detected.', null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for the override', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_overrides', to='monitoring.employee')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
