# Generated by Django 5.2.9 on 2026-05-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_add_clock_time_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['display_order', 'display_name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Sort order for timesheets and employee lists (lower = first)'),
        ),
    ]
